/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gmail.alexei28.shortcut.reactor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        logger.info("\n\n ===== Application started successfully! =====\nЗадача 5 - DLQ, но удобнее");
        logger.info(
                "Java version: {}, Java vendor: {}",
                System.getProperty("java.version"),
                System.getProperty("java.vendor"));
    }
}
